[toolchain]

[build]
docker = true

[compiler]
target = "es6"  # Specify ECMAScript target version
module = "commonjs"  # Specify module code generation
strict = true  # Enable all strict type-checking options
esModuleInterop = true  # Enables emit interoperability between CommonJS and ES Modules
skipLibCheck = true  # Skip type checking of declaration files
forceConsistentCasingInFileNames = true  # Disallow inconsistently-cased references to the same file
types = ["node"]  # Include Node.js types
lib = ["es6", "dom"]  # Include standard ES and DOM libraries


[exclude]
files = ["node_modules"]

[features]
resolution = true
skip-lint = false

[programs.localnet]
t2 = "Program_ID"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
